### ISSUE TITLE
Brew services support

### ISSUE THREAD

**Issue by jonathanwiesel** [fniephaus/alfred-homebrew#1]
Hello there,
Very nice workflow. Have you considered adding support for `brew services`?

It would be extremely useful for managing services (list, start, stop, restart, etc.)

Would be a nice addition to the workflow :wink:

**Comment by kevintraver** [comment]
Looks like it might be easy to integrate with https://github.com/gapple/homebrew-services

**Comment by fniephaus** [comment]
Interesting, but how many people are actually using `gapple/homebrew-services`?
