### ISSUE TITLE
Cask script results in brew-cask usage info

### ISSUE THREAD

**Issue by AlekseyLesnoy** [fniephaus/alfred-homebrew#10]
Hi,

I have a problem with cask script. 
Whenever I try to execute, for example, ```cask list```, brew-cask usage info is showed in Alfred results instead of casks list. Clicking any item in results leads to wrong query execution. (same for ```install / uninstall```, ```search```, ```alfred``` and ```home```)
Brew works fine.

![cask](https://cloud.githubusercontent.com/assets/3266965/10706773/55ba8498-79ea-11e5-9fa0-f03c1fe7fdde.gif)

Cask config:
```
{
  "HOMEBREW_CASK_OPTS": {
    "appdir": "/Applications", 
    "caskroom": "/opt/homebrew-cask/Caskroom"
  }, 
  "__workflow_last_version": "3.1.0"
}
```

Could you please advise any solution?

**Comment by AlekseyLesnoy** [comment]
Well, i guess its brew-cask cli that requires ```[options]``` to be specified after the command, check out  [cask_refresh](https://github.com/fniephaus/alfred-homebrew/blob/master/src/cask_refresh.py#L36)

Usage:
```brew cask command [options] [token ...]```

At least, the sequence change between options and command solved the issue for me.

**Comment by fniephaus** [comment]
@AlekseyLesnoy sorry for the huge delay. I've changed the order and pushed an update (v3.2).
