### ISSUE TITLE
brew or cask commands doesn't extend further

### ISSUE THREAD

**Issue by materemias** [fniephaus/alfred-homebrew#14]
I can type brew or cask in alfred but when I hit tab or space no further commands are displayed nor do work if i type them manually (like brew list)

**Comment by materemias** [comment]
I have the latest from packal, how can I get you a debug log?

**Comment by fniephaus** [comment]
[Here's](https://www.alfredapp.com/help/workflows/advanced/debugger/) how you can get a debug log.

**Comment by materemias** [comment]
the interesting thing is that there is just zero debug info, 

> Starting debug for 'Homebrew & Cask for Alfred'

 is written to the console and no further messages do appear, but executing the commands
`python brew.py` from command line results in

> 13:04:59 workflow.py:2181 DEBUG    update_data : None
13:04:59 workflow.py:1610 DEBUG    Loading cached data from : /Users/me/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_not_installed.cpickle
Traceback (most recent call last):
  File "brew.py", line 156, in <module>
    icon=get_icon("chevron-right")
  File "brew.py", line 62, in get_icon
    name = '%s-dark' % name if is_dark() else name
  File "brew.py", line 67, in is_dark
    rgb = [int(x) for x in WF.alfred_env['theme_background'][5:-6].split(',')]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by fniephaus** [comment]
That is an unrelated error that occurs when executing the script manually (and that's a bug I should fix).
However, your problem seems to be related to #12.

What do you get when running `which brew`?

Unfortunately, I don't have much time at the moment to work on this. But that hopefully changes soon.

**Comment by materemias** [comment]
`which brew
/usr/local/bin/brew`

latest alfred, latest OSX, latest brew, v3.2 of this script

**Comment by fniephaus** [comment]
Interesting, [that](https://github.com/fniephaus/alfred-homebrew/blob/9ba98b858db67b2dc7f85010f221c123d7a32ba5/src/brew_refresh.py#L13) is exactly how the workflow tries to communicate with brew.
What happens when you run the following in a Python shell (just run `python`):
```python
import subprocess
subprocess.Popen(['/usr/local/bin/brew', 'list', '--versions'], stdout=subprocess.PIPE).communicate()
```

**Comment by materemias** [comment]
`>>> import subprocess
>>> subprocess.Popen(['/usr/local/bin/brew', 'list', '--versions'], stdout=subprocess.PIPE).communicate()
('atk 2.18.0_1\nautoconf 2.69\nbash-completion 1.3\nbrew-cask 0.60.1\nbrew-pip 0.4.1\nbyobu 5.101\ncairo 1.14.6_1\ncoreutils 8.25\nddrescue 1.20\nfaac 1.28\nfontconfig 2.11.1_2\nfreetype 2.6.3\ngdbm 1.11\ngettext 0.19.7\nglib 2.46.2\ngnu-sed 4.2.2\ngobject-introspection 1.46.0_1\ngptfdisk 1.0.0_1\nh
icolor-icon-theme 0.15\nhtop-osx 0.8.2.8\nicu4c 56.1\njenv 0.4.3\nlibevent 2.0.22\nlibffi 3.0.13\nlibpng 1.6.21\nlibssh2 1.7.0\nlibtool 2.4.6\nlibusb 1.0.20\nlibusb-compat 0.1.5\nlibvo-aacenc 0.1.3\nmakedepend 1.0.5\nmercurial 3.7.1\nmidnight-commander 4.8.15\nmobile-shell 1.2.5\nnewt 0.52.18\nnode
5.7.0\nntfs-3g 2015.3.14\nopenssl 1.0.2f\npcre 8.38\npixman 0.34.0\npkg-config 0.29\npopt 1.16\nprotobuf 2.6.1\npy2cairo 1.10.0_1\npyenv 20160202\npyenv-virtualenvwrapper 20140609\npygobject 2.28.6\npython 2.7.11\npython3 3.5.1\nreadline 6.3.8\ns-lang 2.3.0\nsiege 3.1.3\nsqlite 3.11.0\ntexi2html 5.0
\nthefuck 3.3\ntmux 2.1\nwakeonlan 0.41\nwatch 3.3.10\nx264 r2601\nxvid 1.3.4\nxz 5.2.2\nyasm 1.3.0\nzsh 5.2\n', None)`

**Comment by materemias** [comment]
if I comment out the first lines of get_icon functions it starts working in the console, interestingly menu loads in alfred once and then stops loading

**Comment by fniephaus** [comment]
Can you replace [this function](https://github.com/fniephaus/alfred-homebrew/blob/9ba98b858db67b2dc7f85010f221c123d7a32ba5/src/brew.py#L55-L58) with:
```python
def brew_not_installed():
    return not os.path.isfile('/usr/local/bin/brew')
```
And then try again?

**Comment by materemias** [comment]
same results, but I think the issue here is not that it doesn't find brew

> 14:17:48 workflow.py:2181 DEBUG    update_data : None
14:17:48 workflow.py:1610 DEBUG    Loading cached data from : /Users/materemias/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_not_installed.cpickle
Traceback (most recent call last):
  File "brew.py", line 159, in <module>
    icon=get_icon("chevron-right")
  File "brew.py", line 65, in get_icon
    name = '%s-dark' % name if is_dark() else name
  File "brew.py", line 70, in is_dark
    rgb = [int(x) for x in WF.alfred_env['theme_background'][5:-6].split(',')]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by fniephaus** [comment]
Yes, because it's not running in Alfred's environment when executed manually.
What happens when you replace [this function](https://github.com/fniephaus/alfred-homebrew/blob/9ba98b858db67b2dc7f85010f221c123d7a32ba5/src/brew.py#L66-L68) with:
```python
def is_dark():
    return true
```

**Comment by materemias** [comment]
then it starts working from command line but not from the app

**Comment by fniephaus** [comment]
So that is not what is causing the problem.
What happens when you replace [this line](https://github.com/fniephaus/alfred-homebrew/blob/9ba98b858db67b2dc7f85010f221c123d7a32ba5/src/brew.py#L81) with `if False:`?

**Comment by materemias** [comment]
console: works
in app: doesn't work

**Comment by fniephaus** [comment]
Could you check what's in your cache directory?
> /Users/materemias/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/

**Comment by materemias** [comment]
brew_all_formulas.cpickle       brew_installed_formulas.cpickle cask_all_casks.cpickle          cask_not_configured.cpickle     cask_refresh.argcache
brew_info.cpickle               brew_not_installed.cpickle      cask_installed_casks.cpickle    cask_not_installed.cpickle      com.fniephaus.homebrew.log

**Comment by fniephaus** [comment]
What's inside one of those files (e.g.`brew_all_formulas.cpickle`)? is it empty?

**Comment by materemias** [comment]
here you can see the sizes

```
54794 Már  3 14:57 brew_all_formulas.cpickle
37 Már  3 14:57 brew_info.cpickle
1142 Már  3 14:57 brew_installed_formulas.cpickle
4 Nov  1 14:07 brew_not_installed.cpickle
223 Már  3 16:03 brew_refresh.argcache
55491 Már  3 14:33 cask_all_casks.cpickle
1054 Már  3 14:33 cask_installed_casks.cpickle
4 Már  1 12:25 cask_not_configured.cpickle
4 Nov  1 14:06 cask_not_installed.cpickle
0 Már  3 14:34 cask_refresh.argcache
562885 Már  3 16:03 com.fniephaus.homebrew.log
```

**Comment by fniephaus** [comment]
Interesting, so it was able to get all the data. I will need to look into this later

**Comment by materemias** [comment]
interestingly the following workflow behaves the same: 
http://www.packal.org/workflow/movie-and-tv-show-search
it is shown up but i cannot extend it. could you please try it? maybe this is an Alfred bug

**Comment by fniephaus** [comment]
Could you check if [v4.0](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.0) resolves your issues?

**Comment by fniephaus** [comment]
Please reopen if the problem persists.

**Comment by materemias** [comment]
this turned out to be a bug in alfred itself! thanks

**Comment by fniephaus** [comment]
Oh wow, thanks!
