### ISSUE TITLE
`alfred` is no longer a cask-supported command

### ISSUE THREAD

**Issue by vitorgalvao** [fniephaus/alfred-homebrew#16]
This workflow allows `alfred` as one of the options for `cask`. However, [we’ve dropped support for the command for a while, now](https://github.com/caskroom/homebrew-cask/pull/14581). In addition, it wasn’t doing much for a while even before that, since Alfred itself added the directories to the scope by itself.

**Comment by fniephaus** [comment]
Thanks, I didn't know. Happy to remove it from this workflow...

**Comment by fniephaus** [comment]
This should be fixed in [v4.2](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.2).
