### ISSUE TITLE
`cask config` shows an error

### ISSUE THREAD

**Issue by vitorgalvao** [fniephaus/alfred-homebrew#17]
Not that I need the option, but it’s erroring out, for me.
![image](https://cloud.githubusercontent.com/assets/1699443/15991123/550ce7a2-30a1-11e6-9bee-7bbb77133cb4.png)

I’ve tried deleting `~/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.homebrew`, and it still happens. The contents of `settings.json` are simply:

```json
{
  "__workflow_last_version": "4.1.0"
}
```

Using Alfred 3.0.1 and latest OS X (10.11.5).

**Comment by fniephaus** [comment]
This should be fixed in [v4.2](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.2).
