### ISSUE TITLE
How to perform a specified terminal command, and then in the execution of the brew?

### ISSUE THREAD

**Issue by banduoba** [fniephaus/alfred-homebrew#19]
In performing the brew command execution, I want a terminal to implement proxy this command,How to set up, please? thank you

**Comment by fniephaus** [comment]
Dear @haoxuexiaoyao,
Sorry, but I'm not sure I understand your question. Could you elaborate, please?

**Comment by samwei12** [comment]
@fniephaus Could you support jump iTerm instead of System Default Terminal?

**Comment by TheSecEng** [comment]
> @fniephaus Could you support jump iTerm instead of System Default Terminal?

iTerm support is Alfred wide. You need to config that at the Alfred level
<img width="1055" alt="Alfred_Preferences" src="https://user-images.githubusercontent.com/32599364/70376948-65528500-18dc-11ea-8699-c561f551f202.png">

**Comment by fniephaus** [comment]
See https://github.com/fniephaus/alfred-homebrew/issues/38#issuecomment-548440281
