### ISSUE TITLE
Plugin uses 100% of CPU until force quit

### ISSUE THREAD

**Issue by boyebn** [fniephaus/alfred-homebrew#25]
I experience that my Mac sometimes gets really hot, at makes a lot of noice. Each time this has happend (~twice a month), the process that is using all the resources are a python-process form this plugin (see image). It keeps using about 100% of the CPU until I force quit it.

<img width="796" alt="skjermbilde 2017-05-19 kl 14 57 10" src="https://cloud.githubusercontent.com/assets/6630430/26248998/d51ff6fe-3ca4-11e7-9c6a-4005b06809cf.png">

I'm not sure if I use the latest version or not. I think I installed the plugin about two months ago.

**Comment by fniephaus** [comment]
Hi @boyebn,
Please update the workflow as this is already addressed in [v4.3](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.3).
Feel free to reopen the issue if the problem persists 😃
