### ISSUE TITLE
Cask install returns an error

### ISSUE THREAD

**Issue by meflouu** [fniephaus/alfred-homebrew#26]
I am getting this error when trying to install:
![error.](http://i.imgur.com/KAx0mRw.png)

**Comment by ErikMinekus** [comment]
```
Error: Warning: Calling \`brew cask\` with the \`--caskroom\` flag is deprecated and will be disabled on 2017-10-31!
```
is probably the real issue.

**Comment by fniephaus** [comment]
The Cask integration definitely needs updating. Any takers? I'm afraid I won't have time to work on this anytime soon...
