### ISSUE TITLE
brew cask search is deprecated

### ISSUE THREAD

**Issue by ErikMinekus** [fniephaus/alfred-homebrew#31]
```brew cask search``` has been deprecated. ```brew search``` now returns formulae and Casks, like so:

```sh
$ brew search github
==> Formulae
github-keygen                         github-markdown-toc                   github-release

==> Casks
github                                github-beta                           githubpulse
```

I don't have the time currently to come up with a fix, but I'm reporting it so other people are aware.

**Comment by ErikMinekus** [comment]
Unfortunately ```brew cask search``` also returns formulae and Casks. These are all formulae, none of the Casks show up:

![cask install github](https://puu.sh/AMKDI/ac8f32892b.png)

**Comment by fniephaus** [comment]
Mh, so the only way to search for casks is to actually call and parse `brew search {search term}`? That's unfortunate and I'm not sure how stable `brew search {something}` is at the moment. Maybe we should just drop support for cask search/install?

**Comment by ErikMinekus** [comment]
Correct. Maybe we can open an feature request to add a flag to ```brew search``` to only return formulae or Casks. I really like being able to search and install Casks from Alfred in one command, so it would be sad to see it go.

**Comment by fniephaus** [comment]
Sound like a good idea. Would you like to work on this? As in filing a feature request and implementing it here once available?

**Comment by ErikMinekus** [comment]
It looks like as of 2 days ago you can run ```brew search --casks``` to get a list of all Casks. If you don't have time to implement that, I'll see if I can get a PR in next week.

**Comment by fniephaus** [comment]
@ErikMinekus cool! I'm afraid next week will be quite busy, but happy to review a PR :)
