### ISSUE TITLE
Getting the error: Cask does not seem to be installed.

### ISSUE THREAD

**Issue by Meflou** [fniephaus/alfred-homebrew#33]
As shown in the image below, even though cask is installed and work normally. I can't do cask config as that returns nothing. I tried both options, the first just opens the website to show you how to install brew, and the second did not fix anything.

![image](https://user-images.githubusercontent.com/10213346/42387188-484ff6b6-814a-11e8-9114-a6cc2677978c.png)

**Comment by ErikMinekus** [comment]
Try running ```brew update``` to make sure your Homebrew installation is up-to-date. If that doesn't solve it, can you run ```brew search --casks``` in Terminal and see if it throws an error?

**Comment by Meflou** [comment]
`brew update` execute fine but `brew search --casks` returns the error: 
`Error: invalid option: --casks`
For what it's worth, the error is also returned when I run that command in my mac where the workflow functions normally. Also, I am sharing the Alfred settings between the two macs.

**Comment by ErikMinekus** [comment]
The ```--casks``` option was added last week, so you either need to update your Homebrew installation, or use an older version of this workflow.

**Comment by fniephaus** [comment]
This should be fixed in [`v5.0`](https://github.com/fniephaus/alfred-homebrew/releases/tag/v5.0).
