### ISSUE TITLE
cask 'dict' object has no atribute 'name'

### ISSUE THREAD

**Issue by R0dri** [fniephaus/alfred-homebrew#35]
Switching to Alfred 4 seems to throw an error on cask. I went back to Alfred 3 to verify it. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/14064394/65700330-7dd93000-e04d-11e9-99ce-55f9ad9e8c5f.png">

Although on Alfred 3, even when doesn't throws an error; it only shows this as an option:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/14064394/65700404-a3663980-e04d-11e9-8dd4-40b5a4f8da2b.png">

With Alfred 3 I can still see the list of casks installed.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/14064394/65700515-d3154180-e04d-11e9-95c6-d6842e9b0898.png">

Here is the error thrown by the debugger console right after I type 'cask' on Alfred 4.

> [11:02:49.655] Homebrew & Cask for Alfred[Script Filter] Queuing argument ''
[11:02:49.837] Homebrew & Cask for Alfred[Script Filter] Script with argv '(null)' finished
[11:02:49.841] ERROR: Homebrew & Cask for Alfred[Script Filter] Code 1: .
11:02:49 workflow.py:2055 DEBUG    ---------- Homebrew & Cask for Alfred (4.8.0) ----------
11:02:49 workflow.py:1462 DEBUG    reading settings from /Users/rodri/Library/Application Support/Alfred/Workflow Data/com.fniephaus.homebrew/settings.json
11:02:49 workflow.py:2339 DEBUG    update check not due
11:02:49 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/__workflow_update_status.cpickle
11:02:49 workflow.py:2269 DEBUG    update_data: {u'available': False}
11:02:49 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_installed.cpickle
11:02:49 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_configured.cpickle
11:02:49 workflow.py:2074 ERROR    'dict' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/rodri/Documents/Alfred.alfredpreferences/workflows/user.workflow.E6B64928-9F26-4A62-A79E-C2B4DB5C8655/workflow/workflow.py", line 2067, in run
    func(self)
  File "cask.py", line 137, in main
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
  File "cask.py", line 137, in <genexpr>
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
AttributeError: 'dict' object has no attribute 'name'
11:02:49 workflow.py:2097 DEBUG    ---------- finished in 0.030s ----------
[11:02:49.842] Homebrew & Cask for Alfred[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Homebrew &amp; Cask for Alfred'</title><subtitle>'dict' object has no attribute 'name'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by fniephaus** [comment]
Hi @R0dri, thanks for the bug report. Could you try clearing the workflow's cache via `brew workflow:delcache`? Does that solve your issue?

**Comment by R0dri** [comment]
still no luck. It takes more time (leading to believe it successfully clears the cache) but same error. Here is the new log from the debug after clearing cache:

>[16:32:54.878] Homebrew & Cask for Alfred[Script Filter] Queuing argument ''
[16:32:58.944] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'i'
[16:32:59.943] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'in'
[16:33:00.319] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'ins'
[16:33:00.567] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'inst'
[16:33:00.760] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'insta'
[16:33:00.967] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'instal'
[16:33:01.144] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'install'
[16:33:02.368] Homebrew & Cask for Alfred[Script Filter] Queuing argument 'install '
[16:33:12.439] Homebrew & Cask for Alfred[Script Filter] Script with argv '(null)' finished
[16:33:12.444] ERROR: Homebrew & Cask for Alfred[Script Filter] Code 1: .
16:32:54 workflow.py:2055 DEBUG    ---------- Homebrew & Cask for Alfred (4.8.0) ----------
16:32:54 workflow.py:1462 DEBUG    reading settings from /Users/rodri/Library/Application Support/Alfred/Workflow Data/com.fniephaus.homebrew/settings.json
16:32:54 workflow.py:2334 INFO     checking for update ...
16:32:54 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/__workflow_update_check.argcache
16:32:54 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/rodri/Documents/Alfred.alfredpreferences/workflows/user.workflow.E6B64928-9F26-4A62-A79E-C2B4DB5C8655/workflow/background.pyc', u'__workflow_update_check']
.
16:32:55 workflow.py:2055 DEBUG    ---------- Homebrew & Cask for Alfred (4.8.0) ----------
16:32:55 background.py:243 DEBUG    [__workflow_update_check] background job started
16:32:55 workflow.py:2269 DEBUG    update_data: None
16:33:09 workflow.py:1724 DEBUG    cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_installed.cpickle
16:33:12 workflow.py:1724 DEBUG    cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_configured.cpickle
16:33:12 workflow.py:2074 ERROR    'dict' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/rodri/Documents/Alfred.alfredpreferences/workflows/user.workflow.E6B64928-9F26-4A62-A79E-C2B4DB5C8655/workflow/workflow.py", line 2067, in run
    func(self)
  File "cask.py", line 137, in main
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
  File "cask.py", line 137, in <genexpr>
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
AttributeError: 'dict' object has no attribute 'name'
16:33:12 workflow.py:2097 DEBUG    ---------- finished in 17.406s ----------
[16:33:12.447] Homebrew & Cask for Alfred[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Homebrew &amp; Cask for Alfred'</title><subtitle>'dict' object has no attribute 'name'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
[16:33:12.637] Homebrew & Cask for Alfred[Script Filter] Script with argv '(null)' finished
[16:33:12.647] ERROR: Homebrew & Cask for Alfred[Script Filter] Code 1: .
16:33:12 workflow.py:2055 DEBUG    ---------- Homebrew & Cask for Alfred (4.8.0) ----------
16:33:12 workflow.py:1462 DEBUG    reading settings from /Users/rodri/Library/Application Support/Alfred/Workflow Data/com.fniephaus.homebrew/settings.json
16:33:12 workflow.py:2339 DEBUG    update check not due
16:33:12 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/__workflow_update_status.cpickle
16:33:12 workflow.py:2269 DEBUG    update_data: {u'available': False}
16:33:12 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_installed.cpickle
16:33:12 workflow.py:1689 DEBUG    loading cached data: /Users/rodri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.fniephaus.homebrew/cask_configured.cpickle
16:33:12 workflow.py:2074 ERROR    'dict' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/rodri/Documents/Alfred.alfredpreferences/workflows/user.workflow.E6B64928-9F26-4A62-A79E-C2B4DB5C8655/workflow/workflow.py", line 2067, in run
    func(self)
  File "cask.py", line 137, in main
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
  File "cask.py", line 137, in <genexpr>
    config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
AttributeError: 'dict' object has no attribute 'name'
16:33:12 workflow.py:2097 DEBUG    ---------- finished in 0.035s ----------
[16:33:12.649] Homebrew & Cask for Alfred[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Homebrew &amp; Cask for Alfred'</title><subtitle>'dict' object has no attribute 'name'</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by fniephaus** [comment]
What if you remove and re-install the workflow?

**Comment by R0dri** [comment]
No luck. Tried brew doctor just in case but seems to have the same behavior.

**Comment by fniephaus** [comment]
That's odd. The [line of error](https://github.com/fniephaus/alfred-homebrew/blob/6f4b4f0f9b779a558bd8e4bd96c04e437079fcf3/src/cask.py#L137) iterates over a [well-defined list of dictionaries](https://github.com/fniephaus/alfred-homebrew/blob/master/src/cask_actions.py), all of which have an attribute `name`. Do you have Python 3 installed as your default `python`?

**Comment by fniephaus** [comment]
I've just upgraded the `alfred-workflow` dependency of the workflow and released it as [`v4.9`](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.9). Could you please give that a try?

**Comment by R0dri** [comment]
looks like I am on python 2.7 as default. I upgraded the workflow and same thing.

**Comment by fniephaus** [comment]
Too bad, I'm running out of ideas for async debugging. What happens if you cd into the workflow's directory and execute `python cask.py` in a terminal?

**Comment by cocobear** [comment]
I'm got same error, when execute `python cask.py1 results:
* Python 2.7.10
*  ---------- Homebrew & Cask for Alfred (4.9.0) ----------
* workflow/version 1.37.2


> .
> 12:47:13 workflow.py:2338 INFO     checking for update ...
> .
> 12:47:27 workflow.py:2080 ERROR    'dict' object has no attribute 'name'
> Traceback (most recent call last):
>   File "/Users/cocobear/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.EBA6E5A5-20AE-413D-9C9B-9DC93F659369/workflow/workflow.py", line 2073, in run
>     func(self)
>   File "cask.py", line 137, in main
>     config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
>   File "cask.py", line 137, in <genexpr>
>     config = next(a for a in cask_actions.ACTIONS if a.name == 'config')
> AttributeError: 'dict' object has no attribute 'name'

**Comment by fniephaus** [comment]
What do you seen when you run `brew search --casks` in your terminal?

**Comment by cocobear** [comment]
brew search --casks | head

> 0-ad
> 010-editor
> 0xed
> 115browser
> 1clipboard
> 1password
> 1password-beta
> 1password-cli
> 1password6
> 245cloud
> ...


a lot of outputs.

**Comment by R0dri** [comment]
I could manage to do a bunch of tests and got interesting results:

1. If I modify brew.py and add '--cask' at
`def get_all_formulae():
    return execute(['brew', 'search', '--cask']).splitlines()`
it works; returning the correct list of cask packages instead of brew ones.

2. changing a.name to a['name'] removes the error but then:
3. Cask.py defaults to a bad config for an unknown reason:
If tweaking the code a little; removing 'not' at the following
` elif not wf.cached_data('cask_configured', _cask_configured, max_age=0):`
Removes all warnings and displays cask options. Even the search works. But when trying to install a package only "Config" appears: 
![image](https://user-images.githubusercontent.com/14064394/65884535-05cd7b80-e367-11e9-8c30-8e759f24ce14.png)


Now I am stuck here. I believe that result is because there is 'sudo' at the result.

	new_env = os.environ.copy()
    new_env['PATH'] = '/usr/local/bin:%s' % new_env['PATH']
    result, err = subprocess.Popen(cmd_list,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE,
                                   env=new_env).communicate()
    if err:
        return 'Error: %s' % err

    if 'sudo' in result:
        return 'Config'

    return result

**Comment by ErikMinekus** [comment]
Seems like there is now a [font-sudo](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-sudo.rb) Cask, so this check breaks `cask install`:
```py
if 'sudo' in result:
    return 'Config'
```
I guess this check is there in case you changed `HOMEBREW_CASK_OPTS`? Maybe there's a better way to check for that?

**Comment by TheSecEng** [comment]
Fixed with PR https://github.com/fniephaus/alfred-homebrew/pull/36

**Comment by R0dri** [comment]
Just tested new version. But as I mentioned:

> 2. changing a.name to a['name'] removes the error but then:

But then it appears as not properly configured. I believe @ErikMinekus pointed out where the exception now lies:


> Seems like there is now a [font-sudo](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-sudo.rb) Cask, so this check breaks `cask install`:
> 
> ```python
> if 'sudo' in result:
>     return 'Config'
> ```
> 
> I guess this check is there in case you changed `HOMEBREW_CASK_OPTS`? Maybe there's a better way to check for that?

**Comment by TheSecEng** [comment]
> Just tested new version. But as I mentioned:
> 
> > 1. changing a.name to a['name'] removes the error but then:
> 
> But then it appears as not properly configured. I believe @ErikMinekus pointed out where the exception now lies:
> 
> > Seems like there is now a [font-sudo](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-sudo.rb) Cask, so this check breaks `cask install`:
> > ```python
> > if 'sudo' in result:
> >     return 'Config'
> > ```
> > 
> > 
> > I guess this check is there in case you changed `HOMEBREW_CASK_OPTS`? Maybe there's a better way to check for that?

Can you open a new issue and I will push a PR shortly

**Comment by R0dri** [comment]
Done #39, Thanks for the attention.
