### ISSUE TITLE
Update paths to not be hardcoded

### ISSUE THREAD

**Issue by ModdedGamers** [fniephaus/alfred-homebrew#44]
### Motivation

I run a custom brew install (no access to /usr/local), so this workflow does not work.

### Proposed Solution

Replace the hardcoded paths with variables that can be set on install.

### Alternatives

The alternative is hardcoded paths, which don't work because then there is no support for users like me.

### Additional Context
N/A

**Comment by fniephaus** [comment]
I believe this has been addressed in #46: you can now enter `brew config` to change the configuration file.

**Comment by ModdedGamers** [comment]
Thanks!
