### ISSUE TITLE
Deprecated api causes no results

### ISSUE THREAD

**Issue by ttuygun** [fniephaus/alfred-homebrew#47]
### Describe the Bug

Brew search/install produces no results with deprecation errors.

### Steps to Reproduce

1. Write brew search a (or brew install)
2. Observe error

### Expected Behavior

Listing available packages that starts with a

### Actual Behavior

Shows error like that:
brew install Warning: Calling 'brew search' with no arguments to output formulae is deprecated! Use 'brew formulae' instead.

### Additional Context

![image](https://user-images.githubusercontent.com/10091984/105577858-2ce66280-5d8d-11eb-98ba-60001aece6bf.png)

Homebrew 2.7.5
macOS 11.1

**Comment by fniephaus** [comment]
This was just fixed in [`5.3`](https://github.com/fniephaus/alfred-homebrew/releases/tag/v5.3) via https://github.com/fniephaus/alfred-homebrew/pull/46/commits/525caccacb7685dc9be40b55d98d3c2facfb1a8d.
