### ISSUE TITLE
cask search and install returns an error

### ISSUE THREAD

**Issue by meflouu** [fniephaus/alfred-homebrew#48]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/29525006/114989097-c3638500-9e9f-11eb-8964-ef68fb78b76f.png">

**Comment by fniephaus** [comment]
Hi @meflouu,

I noticed this last night as well. Not sure what caused the problem, but manually upgrading brew (run `brew update` in a terminal) and then clearing the workflow's cache (type in `brew workflow:delcache` into Alfred) fixed it. Please re-open this issue if the steps don't work for you.
