### ISSUE TITLE
brew search results in alfred searching google instead of brew

### ISSUE THREAD

**Issue by jaduff** [fniephaus/alfred-homebrew#5]
Typing 'brew search' into alfred, or typing 'brew sea' and using alfred to complete the 'search' keyword results in a google search of the whole string.
Example: 'brew search duti' launches a browser with a google search for 'brew search duti'.

![image](https://cloud.githubusercontent.com/assets/10690970/5889987/8f3accfc-a47d-11e4-9091-72c0b7141a6a.png)

**Comment by fniephaus** [comment]
Sorry for that. I'll push an update in a couple of hours...

**Comment by jaduff** [comment]
Wow! Quick!
Thanks Fabio, working for me.

**Comment by fniephaus** [comment]
You're welcome.
Thanks for reporting the problem.
