### ISSUE TITLE
I have a path problem when using this workflow, don't you have?

### ISSUE THREAD

**Issue by FischLu** [fniephaus/alfred-homebrew#51]
While, the workflow doesn't work on my M1 mac, I got some error message in the debug window of Alfred
```
  File "brew.py", line 41, in get_outdated_formulae
    return execute(wf, ['brew', 'outdated', '--formula']).splitlines()
  File "brew.py", line 22, in execute
    env=new_env).communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I see `return execute(wf, ['brew', 'outdated', '--formula']).splitlines()` and my homebrew installation path is `/opt/homebrew/bin/brew`, this path is not in the Alfred bash environment variable $PATH. So I changed `brew` from the command to its full path and now the workflow works fine, but why don't you have this problem? I didn't change the default installation path of homebrew, is yours in the same place?

**Comment by fniephaus** [comment]
No, I didn't change the default installation path of Homebrew. I don't know why your Homebrew installation is not on the path that Alfred uses. I don't have an M1 Mac, so I can't really try and reproduce your issue. Maybe it's something you can fix within Alfred, it could also be a problem with the Python Alfred is using.
Changing the command to the full path is a workaround but it will probably break with the next update (the workflow isn't updated often though).

**Comment by FischLu** [comment]
I figured out the reason, the default installation path of Homebrew on M1 mac is /opt/homebrew/bin/brew, although I don't know why they do this. Therefore, instead of using full path, I can use this script in the script filter
```bash
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
python cask.py "{query}"
```
Maybe this can provide some help to other users who have the same problem.

**Comment by fniephaus** [comment]
Still it's weird that `brew` does not work. I assume you can call that directly from your terminal. Are you sure the path is set in your zsh environment, which I think is what Alfred is using?

**Comment by FischLu** [comment]
That's because Alfred shell doesn't load user's profile, it only use default system environment path, as mentioned [here](https://www.alfredforum.com/topic/3500-command-not-found-%E2%80%94-path-issue/)
