### ISSUE TITLE
iTerm2 Support

### ISSUE THREAD

**Issue by altern8tif** [fniephaus/alfred-homebrew#6]
Current `brew` and `cask` commands are opened in Terminal.app.  Would it be possible to open in iTerm2 instead?

**Comment by fniephaus** [comment]
It is already possible to use iTerm2 by default.
Simply select it in your Alfred Preferences (`Features` -> `Terminal / Shell` -> `Application`) and it should work!

**Comment by altern8tif** [comment]
Ah... Wondering how I missed that.  Thanks!

**Comment by fniephaus** [comment]
No worries! :smile:
