### ISSUE TITLE
cask command prompt "sudo: no tty present and no askpass program specified"

### ISSUE THREAD

**Issue by roddehugo** [fniephaus/alfred-homebrew#7]
When I try to use one of the following cask command `list | search | install | uninstall` (i.e: any command which uses one of `get_all_casks()` or `get_installed_casks()` method), I get this item added to alfred list `sudo: no tty present and no askpass program specified`.

I investigated a little using debug mode and found that I needed to add my own `export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"` right after `[export PATH](https://github.com/fniephaus/alfred-homebrew/blob/master/src/cask_refresh.py#L21)` because I'm tweaking where Homebrew Cask is installed and where it installs my applications.

This may be useful to other people in the future.

BTW, thanks for your awesome work! It perfectly suits my needs.

**Comment by fniephaus** [comment]
Thanks @roddehugo.
If you could add your instructions to the `README.md` file, I'd be happy to merge this in.
