### ISSUE TITLE
Could you share your theme?

### ISSUE THREAD

**Issue by bpinto** [fniephaus/alfred-homebrew#9]
Sorry for creating an issue.

**Comment by fniephaus** [comment]
Hi @bpinto,
No problem. I guess you are looking for this :smiley: 
http://www.packal.org/theme/monokai-reloaded

Best,
Fabio

**Comment by bpinto** [comment]
Hey, thanks! Sorry to bug you in the wrong repo! By the way, awesome theme and tool!

**Comment by fniephaus** [comment]
No worries! And thanks :smiley:
